### ISSUE TITLE
Firstboot Scripts and Pkgs

### ISSUE THREAD

**Issue by mholttech** [grahamgilbert/puppet-outset#1]
I was wondering if this actually works.  From what I understand, outset deletes firstboot files after they are run but puppet ensures they exist on every run so what i'm seeing is there is no way to truly run a firstboot script deployed through puppet.  Do you have any suggestions?

**Comment by grahamgilbert** [comment]
You are correct, it won't work - I have clearly never used it for first boot scripts and blindly made the module without thinking. I will take them out.
